timezone: America/New_York
title: The Alley | Makerspace
collections:
  alley_crew:
    output: false
  advisors:
    output: false
  projects:
    output: true
  wikis:
    output: true
  events:
    output: true

facebook_url: https://www.facebook.com/makerspacemtu/
twitter_url: https://twitter.com/makerspacemtu
email_address: makerspace@mtu.edu
email_updates_url: http://eepurl.com/bKQAsf
